import * as InputCounter from "./modules/input-counter.js";
import * as MoreBlocks from "./modules/more-blocks.js";
import * as Burger from "./modules/burger.js";
import * as Menu from "./modules/menu.js";
import * as AnimateScroll from "./modules/animate-scroll.js";
import * as ShowMenu from "./modules/show-menu.js";
import * as CheckboxActive from "./modules/checkbox-active.js";
import * as Pagination from "./modules/pagination.js";
import * as JS from "./modules/js.js";